[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**, .next/**, **/cache/**"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://connect.facebook.net; img-src 'self' data: https://www.facebook.com https://www.google-analytics.com; connect-src 'self' https://connect.facebook.net https://www.facebook.com https://www.google-analytics.com https://region1.google-analytics.com; style-src 'self' 'unsafe-inline'; font-src 'self';"
